# Session 1 - visual

In [6]:
# playing with strings
text_snippet = "This is some text, indeed it is"
text_snippet.split()
text_snippet.upper()
text_snippet.lower()

'this is some text, indeed it is'

In [4]:
text_snippet.split(",") #splitting with the comma - into a list 

['This is some text', ' indeed it is']

## Sequence types - list


In [7]:
colours = ["blue", "green", "red"]

In [10]:
colours[-1]

'red'

In [11]:
user_data = ["mary", 42, 1.65]

In [12]:
big_list = [user_data, colours]

In [13]:
big_list

[['mary', 42, 1.65], ['blue', 'green', 'red']]

In [19]:
big_list[0][1]

42

In [26]:
colours.append("yellow")
colours.remove("green")

## Tuples

In [27]:
colours_tuple = ("blue", "green", "red")

## Dictionaries
 

In [30]:
user_ages = {"Mary": 42,
             "John": 34}

In [29]:
user_ages["Mary"]

42

In [31]:
new_users = dict(mary=[42, 1.65],
                john=[50, 1.80], 
                alice=[24, 1.83])

In [37]:
new_users = dict(mary = {"age": 42, "height": 1.65},
                john = {"age": 50, "height": 1.80}, 
                alice = {"age": 24, "height": 1.83})

In [38]:
new_users["mary"]["age"]

42

## Number types

In [39]:
float(2) # coercing the integer into a float

2.0

In [50]:
number = 3.7
print(int(round(number)))
type(number)

4


float

In [51]:
11//2 # gives integer
10/2 # gives float

5.0

## Boolean (bool) types

In [52]:
True == 1

True

In [53]:
False == 0

True

## Introducing ```numpy``` Arrays

In [55]:
# Pip is the main package installer for Python
# in terminal write pip install numpy 

import numpy as np
import os

In [81]:
# Create file path
print(os.getcwd()) #see where you are - 3 steps up to work

filepath = os.path.join("..", 
                        "..",
                        "..",
                        "cds-vis-data", 
                        "data",
                        "sample-data",
                        "sample-data-01.csv")

/work/CDS-visual/CDS-visual/Notebooks


In [84]:
data = np.loadtxt(fname=filepath, delimiter=",")

In [85]:
data.dtype

dtype('float64')

In [101]:
type(data)

numpy.ndarray

In [86]:
data.shape

(60, 40)

In [87]:
data[0,0]

0.0

In [89]:
data[-1, -1]

0.0

In [96]:
# array slice
print(data[:4, :10])
print(data[0:4, 0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]
[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]


In [97]:
# select whole row
data[0,:]

array([ 0.,  0.,  1.,  3.,  1.,  2.,  4.,  7.,  8.,  3.,  3.,  3., 10.,
        5.,  7.,  4.,  7.,  7., 12., 18.,  6., 13., 11., 11.,  7.,  7.,
        4.,  6.,  8.,  8.,  4.,  4.,  5.,  7.,  3.,  4.,  2.,  3.,  0.,
        0.])

In [98]:
# average score
np.mean(data)

6.14875

In [100]:
np.max(data, axis=1) # max value per row
np.min(data, axis=0) # min value per column

array([0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3., 4.,
       5., 5., 5., 5., 4., 4., 4., 4., 3., 3., 3., 3., 2., 2., 2., 2., 1.,
       1., 1., 1., 0., 0., 0.])